# Generated by Django 3.2.8 on 2021-10-18 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain2',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='blockchain',
            name='product_name_plural',
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.IntegerField()),
                ('miner_id', models.CharField(max_length=16)),
                ('payload', models.CharField(blank=True, max_length=200, null=True)),
                ('nonce', models.CharField(blank=True, max_length=60, null=True)),
                ('prev_hash', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcsim.blockchain')),
            ],
        ),
    ]
