# Generated by Django 3.2.8 on 2021-10-14 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0002_remove_blockchain_product_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.IntegerField()),
                ('miner_id', models.CharField(max_length=16)),
                ('payload', models.CharField(max_length=200)),
                ('nonce', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blockchain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcsim.blockchain')),
            ],
        ),
    ]
