# Generated by Django 3.2.8 on 2021-10-18 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0002_auto_20211018_0959'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blockchain2',
        ),
    ]
