# Generated by Django 3.2.8 on 2021-10-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0003_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='prev_hash',
            field=models.CharField(default='hej', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='title',
            field=models.CharField(max_length=63),
        ),
    ]
