# Generated by Django 3.2.8 on 2021-10-15 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0004_auto_20211015_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='blockchain_id',
            new_name='blockchain',
        ),
    ]
