# Generated by Django 3.2.8 on 2021-10-15 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0005_rename_blockchain_id_block_blockchain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='block_id',
            new_name='block_num',
        ),
    ]
