# Generated by Django 3.2.8 on 2021-10-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0006_rename_block_id_block_block_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='created_at',
        ),
    ]
