# Generated by Django 3.2.8 on 2021-12-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0006_rename_trader_miner'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='creator_name',
            field=models.CharField(default='Blockchain creator', max_length=36),
        ),
    ]
