# Generated by Django 3.2.8 on 2021-12-01 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0007_blockchain_creator_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='miner_id',
        ),
    ]
