# Generated by Django 3.2.8 on 2021-12-01 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0008_remove_block_miner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='block_id',
        ),
        migrations.AddField(
            model_name='block',
            name='miner',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='bcsim.miner'),
            preserve_default='True',
        ),
    ]
