# Generated by Django 3.2.8 on 2021-10-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0008_block_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
