# Generated by Django 3.2.8 on 2021-12-06 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0009_auto_20211201_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='block_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='block',
            name='miner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bcsim.miner'),
        ),
    ]
