# Generated by Django 3.2.8 on 2021-10-16 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0009_alter_block_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='block_num',
            new_name='block_id',
        ),
    ]
