# Generated by Django 3.2.8 on 2021-10-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0010_rename_block_num_block_block_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
