# Generated by Django 3.2.8 on 2021-12-06 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0011_alter_block_block_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='miner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcsim.miner'),
        ),
    ]
