# Generated by Django 3.2.8 on 2021-12-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0012_alter_block_miner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='payload',
            field=models.CharField(max_length=200),
        ),
    ]
