# Generated by Django 3.2.8 on 2021-12-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0013_alter_block_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
