# Generated by Django 3.2.8 on 2021-12-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0014_alter_miner_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='creator_name',
            field=models.CharField(default='Skaber', max_length=36),
        ),
    ]
