# Generated by Django 3.2.8 on 2021-12-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0016_miner_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner',
            name='miner_id',
            field=models.IntegerField(null=True),
        ),
    ]
