# Generated by Django 3.2.8 on 2021-12-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0017_miner_miner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner',
            name='creator',
            field=models.BooleanField(default=False),
        ),
    ]
