# Generated by Django 3.2.8 on 2021-12-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0018_miner_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miner',
            old_name='miner_id',
            new_name='miner_num',
        ),
    ]
