# Generated by Django 3.2.8 on 2021-12-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0019_rename_miner_id_miner_miner_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miner',
            name='id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
