# Generated by Django 3.2.8 on 2022-01-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0020_alter_miner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=2),
        ),
    ]
