# Generated by Django 3.2.8 on 2022-01-11 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0021_blockchain_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockchain',
            old_name='status',
            new_name='difficulty',
        ),
    ]
