# Generated by Django 3.2.8 on 2022-01-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0022_rename_status_blockchain_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nem'), (2, 'Medium'), (3, 'Svær')], default=2),
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='title',
            field=models.CharField(default='Transaktioner', max_length=50),
        ),
    ]
