# Generated by Django 3.2.8 on 2022-01-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0023_auto_20220111_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='paused',
            field=models.BooleanField(default=False),
        ),
    ]
