# Generated by Django 3.2.8 on 2022-01-24 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0027_alter_block_nonce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='block_id',
            new_name='block_num',
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.CharField(max_length=10)),
                ('miner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcsim.miner')),
            ],
        ),
    ]
