# Generated by Django 3.2.8 on 2022-01-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0028_auto_20220124_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner',
            name='number_of_last_block_seen',
            field=models.IntegerField(default=0),
        ),
    ]
