# Generated by Django 3.2.8 on 2022-01-25 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0029_miner_number_of_last_block_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miner',
            old_name='creator',
            new_name='is_creator',
        ),
    ]
