# Generated by Django 3.2.8 on 2022-01-25 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0030_rename_creator_miner_is_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockchain',
            old_name='paused',
            new_name='is_paused',
        ),
    ]
