# Generated by Django 3.2.8 on 2022-01-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0031_rename_paused_blockchain_is_paused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nem'), (2, 'Middel'), (3, 'Svær')], default=2),
        ),
    ]
