# Generated by Django 3.2.8 on 2022-02-01 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0032_alter_blockchain_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='miner_id',
            new_name='owner',
        ),
    ]
