# Generated by Django 3.2.8 on 2022-02-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0033_rename_miner_id_token_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
