# Generated by Django 3.2.8 on 2022-02-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0034_token_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
