# Generated by Django 3.2.8 on 2022-02-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0036_alter_block_block_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='nonce',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
