# Generated by Django 3.2.8 on 2022-02-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0039_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='is_simple',
            field=models.BooleanField(default=True),
        ),
    ]
