# Generated by Django 3.2.8 on 2022-02-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0040_blockchain_is_simple'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Uden marked'), (2, 'Med marked')], default=1),
        ),
    ]
