# Generated by Django 3.2.8 on 2022-02-01 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0041_blockchain_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bcsim.transaction'),
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Uden token-marked'), (2, 'Med token-marked')], default=1),
        ),
    ]
