# Generated by Django 3.2.8 on 2022-02-01 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0042_auto_20220201_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bcsim.miner'),
        ),
    ]
