# Generated by Django 3.2.8 on 2022-02-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0043_auto_20220201_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchain',
            name='is_simple',
        ),
    ]
