# Generated by Django 3.2.8 on 2022-02-01 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0046_transaction_blockchain'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='blockchain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bcsim.blockchain'),
        ),
    ]
