# Generated by Django 3.2.8 on 2022-02-01 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0047_token_blockchain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='blockchain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bcsim.blockchain'),
        ),
    ]
