# Generated by Django 3.2.8 on 2022-02-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0048_alter_transaction_blockchain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='available',
        ),
        migrations.AddField(
            model_name='token',
            name='on_market',
            field=models.BooleanField(default=False),
        ),
    ]
