# Generated by Django 3.2.8 on 2022-02-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0052_rename_in_queue_transaction_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
