# Generated by Django 3.2.8 on 2022-02-03 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0053_alter_transaction_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
    ]
