# Generated by Django 3.2.8 on 2022-02-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0056_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
