# Generated by Django 3.2.8 on 2022-02-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0058_auto_20220203_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='on_market',
            new_name='trade_in_process',
        ),
    ]
