# Generated by Django 3.2.12 on 2022-02-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0059_rename_on_market_token_trade_in_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='trade_in_process',
        ),
        migrations.AddField(
            model_name='token',
            name='transaction_in_process',
            field=models.BooleanField(default=True),
        ),
    ]
