# Generated by Django 3.2.12 on 2022-02-08 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0060_auto_20220207_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bcsim.token'),
        ),
    ]
