# Generated by Django 3.2.12 on 2022-02-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcsim', '0062_alter_transaction_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Uden NFT-marked'), (2, 'Med NFT-marked')], default=1),
        ),
    ]
