version: "3.3"
   
services:
  web:
    build: .
    command: /bin/sh -c /code/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
     - db
     
  db:
    image: postgres:14
    volumes:
     - database_volume:/var/lib/postgresql/data/
    environment:
     - "POSTGRES_HOST_AUTH_METHOD=trust"
    env_file:
      - .env.dev
    user: postgres:postgres

volumes:
  database_volume: {}