version: "3.3"
   
services:
  web:
    build: .
    command: /bin/sh -c /code/entrypoint.sh
    volumes:
      - database_volume:/db/
      - .:/code
    ports:
      # "host:container"
      - "8000:8000"
    env_file:
      - ./.env.dev

volumes:
  database_volume: {}